import type { ColumnMetadata, EntityMetadata } from '@ts-linq/types';

import type { Dialect } from '../../Dialect';
import type { ColumnDef, TableSnapshot } from '../../DiffTypes';
import { QuoterFactory } from '../quoting/QuoterFactory';

/**
 * Shape bridge between the migration snapshot model (`ColumnDef`/`TableSnapshot`) and the
 * `EntityMetadata`/`ColumnMetadata` shapes the shared `DdlStrategy` speaks. It carries no DDL
 * knowledge of its own — no type mapping, no identifier quoting, no dialect branching beyond
 * resolving the snapshot's per-dialect default expression.
 */

/**
 * Resolves the `DEFAULT` fragment to a SQL *expression* before handing the column to the strategy.
 *
 * Two snapshot features have no counterpart in `ColumnMetadata`:
 * 1. `defaultExpressionDialect` — a per-dialect override of `defaultExpression`;
 * 2. literal defaults, which migrations renders through its own audited {@link SqlQuoter}
 *    (`migrations/task-1`), whose boolean encoding is dialect-aware (`TRUE`/`FALSE` on PostgreSQL)
 *    unlike the dialect-kit `formatValue` (`1`/`0`). Unifying those two literal encoders is
 *    `dialect-postgres/task-11`; until then the literal is pre-rendered here so the strategy takes
 *    its expression branch and the emitted SQL is unchanged.
 */
function resolveDefaultExpression(dialect: Dialect, column: ColumnDef): string | undefined {
  const perDialect = column.defaultExpressionDialect?.[dialect];
  const expression = perDialect || column.defaultExpression;
  if (expression) return expression;
  if (column.defaultValue === undefined) return undefined;
  return QuoterFactory.for(dialect).literal(column.defaultValue);
}

/**
 * Adapts one snapshot column to the `ColumnMetadata` shape.
 *
 * Deliberately left unset: `isGenerated` (would make PostgreSQL emit `GENERATED BY DEFAULT AS
 * IDENTITY` and MySQL `AUTO_INCREMENT`) and `length`/`precision`/`scale` — the snapshot model has no
 * such fields, and the physical type it carries is already fully formed.
 */
export function toColumnMetadata(dialect: Dialect, column: ColumnDef): ColumnMetadata {
  return {
    propertyName: column.name,
    columnName: column.name,
    type: column.type,
    nullable: column.nullable,
    comment: column.comment,
    isComputed: column.isComputed,
    computedExpression: column.computedExpression,
    computedStorage: column.computedStorage,
    defaultExpression: resolveDefaultExpression(dialect, column)
  };
}

/**
 * Wraps already-adapted columns in the minimal `EntityMetadata` the strategy needs to build the
 * `PRIMARY KEY (…)` clause. Takes the adapted columns rather than the snapshot so the caller, which
 * has already mapped them for the column definitions, does not pay a second adaptation pass.
 * `relationships`/`indexes` are required by the interface but unused on that path — migrations
 * emits foreign keys and indexes through its own builders.
 */
export function toEntityMetadata(table: TableSnapshot, columns: ColumnMetadata[]): EntityMetadata {
  return {
    tableName: table.name,
    columns,
    relationships: [],
    indexes: [],
    primaryKeys: table.primaryKeys
  };
}
