import type {
  CheckConstraintMetadata,
  ColumnMetadata,
  IndexMetadata,
  RelationshipMetadata
} from '@ts-linq/types';

// ─── Sub-model types ──────────────────────────────────────────────────────────

/** Serializable shadow property (no Map — safe for as-const objects). */
export interface CompiledShadowPropertyModel {
  readonly propertyName: string;
  readonly columnName: string;
  readonly type: string;
  readonly nullable?: boolean;
  readonly defaultValue?: unknown;
  readonly defaultExpression?: string;
  readonly comment?: string;
  readonly length?: number;
  readonly precision?: number;
  readonly scale?: number;
}

/** Serializable alternate key. */
export interface CompiledAlternateKeyModel {
  readonly name: string;
  readonly columns: readonly string[];
}

/** Serializable skip navigation (many-to-many). */
export interface CompiledSkipNavigationModel {
  readonly propertyName: string;
  readonly targetEntityClassName: string;
  readonly joinTableName: string;
  readonly joinEntityClassName: string;
  readonly leftForeignKey: string;
  readonly rightForeignKey: string;
  readonly inverseSide?: string;
  readonly isSynthesized: boolean;
}

/** Serializable owned entity relationship. */
export interface CompiledOwnedEntityModel {
  readonly ownerPropertyName: string;
  readonly ownedTypeClassName: string;
  readonly strategy: string;
  readonly columnPrefix?: string;
  readonly jsonColumnName?: string;
  readonly foreignKeyColumns?: readonly string[];
  readonly principalKeyColumns?: readonly string[];
  readonly compositeKeyColumns?: readonly string[];
  readonly isCollection: boolean;
}

/** Serializable hierarchy metadata. */
export interface CompiledHierarchyModel {
  readonly strategy: string;
  readonly rootEntityClassName: string;
  readonly subtypeClassNames: readonly string[];
  readonly discriminator?: {
    readonly columnName: string;
    readonly columnType: string;
    readonly isComplete: boolean;
    readonly entries: ReadonlyArray<{
      readonly ctorClassName: string;
      readonly value: unknown;
    }>;
  };
}

// ─── Per-entity model ─────────────────────────────────────────────────────────

/** Serializable snapshot of a single entity's metadata. */
export interface CompiledEntityModel {
  readonly entityClassName: string;
  readonly tableName: string;
  readonly schema?: string;
  readonly primaryKeys?: readonly string[];
  readonly columns: ReadonlyArray<ColumnMetadata>;
  readonly relationships: ReadonlyArray<RelationshipMetadata>;
  readonly indexes: ReadonlyArray<IndexMetadata>;
  readonly checkConstraints?: ReadonlyArray<CheckConstraintMetadata>;
  readonly shadowProperties?: ReadonlyArray<CompiledShadowPropertyModel>;
  readonly alternateKeys?: ReadonlyArray<CompiledAlternateKeyModel>;
  readonly skipNavigations?: ReadonlyArray<CompiledSkipNavigationModel>;
  readonly ownedEntities?: ReadonlyArray<CompiledOwnedEntityModel>;
  readonly hierarchy?: CompiledHierarchyModel;
  readonly hierarchyRootClassName?: string;
  readonly isTemporal?: boolean;
  readonly historyTableName?: string;
  readonly isKeyless?: boolean;
  readonly viewName?: string;
  readonly viewSql?: string;
  readonly comment?: string;
  readonly seedData?: ReadonlyArray<Record<string, unknown>>;
}

// ─── Top-level compiled model ─────────────────────────────────────────────────

/**
 * AOT-compiled snapshot of all entity metadata for a single DbContext.
 * Generated by: `pnpm ts-linq dbcontext optimize`
 * Consumed by: `DbContextOptions.compiledModel`
 *
 * When present, DbContext pre-populates MetadataRegistry from this snapshot
 * and skips the reflective decorator scan on startup.
 *
 * Note: queryFilters are NOT included — they contain compiled AST lambda nodes
 * that cannot be serialised. onModelCreating is still called in both paths for
 * query filters and fluent-API runtime overrides.
 */
export interface CompiledModel {
  readonly version: 1;
  readonly contextClassName: string;
  /** ISO-8601 timestamp written at generation time — used for drift-detection. */
  readonly generatedAt: string;
  readonly entities: ReadonlyArray<CompiledEntityModel>;
}
