import { AbstractDdlStrategy, type DdlLoggerLike } from '@ts-linq/dialect-kit';
import type { ColumnMetadata, DdlStrategy, EntityMetadata, TypeMapper } from '@ts-linq/types';

import { PgIndexBuilder } from './builders/PgIndexBuilder';
import { PostgresTypeMapper } from './PostgresTypeMapper';
import { quoteIdentifier, quoteStringLiteral } from './quoting';

/**
 * PostgreSQL DDL strategy. The invariant CREATE TABLE / ALTER / FK / constraint / comment algorithms
 * live in {@link AbstractDdlStrategy}; this class supplies only the PG `TypeMapper` and the divergent
 * hooks (identity columns, `GENERATED … STORED`, `COMMENT ON …`, `DROP CONSTRAINT IF EXISTS`).
 */
export class PostgresDdlStrategy extends AbstractDdlStrategy implements DdlStrategy {
  protected readonly addColumnClause = 'ADD COLUMN';
  private readonly indexBuilder: PgIndexBuilder;

  constructor(logger?: DdlLoggerLike, typeMapper: TypeMapper = new PostgresTypeMapper()) {
    super(logger, typeMapper);
    this.indexBuilder = new PgIndexBuilder(logger);
  }

  protected quoteIdentifier(identifier: string): string {
    return quoteIdentifier(identifier);
  }

  protected quoteStringLiteral(value: string): string {
    return quoteStringLiteral(value);
  }

  /** Public logical→physical type map. Retained for backward compatibility (delegates to the mapper). */
  public mapTypeToPg(type: string): string {
    return this.typeMapper.mapType(type);
  }

  public generateCreateIndexSql(
    table: string,
    index: {
      name: string;
      columns: string[];
      unique: boolean;
      where?: string;
      orders?: { [column: string]: 'ASC' | 'DESC' };
      expressions?: string[];
      collations?: { [column: string]: string };
      nulls?: { [column: string]: 'FIRST' | 'LAST' };
      using?: 'btree' | 'hash' | 'gin' | 'gist';
      concurrently?: boolean;
      withParams?: Record<string, string | number | boolean>;
    }
  ): string {
    return this.indexBuilder.buildCreateIndexSql(table, index);
  }

  protected wrapCreateTable(metadata: EntityMetadata, body: string): string {
    return `CREATE TABLE IF NOT EXISTS ${this.quoteIdentifier(metadata.tableName)} (${body})`;
  }

  protected renderComputedColumn(column: Omit<ColumnMetadata, 'propertyName'>): string {
    // PostgreSQL supports only STORED generated columns.
    const storage = column.computedStorage;
    if (storage && storage !== 'STORED') {
      this.logger?.warn(
        `Postgres: computedStorage='${storage}' is not supported; coercing to STORED for ${column.columnName}`
      );
    }
    return `${this.quoteIdentifier(column.columnName)} ${this.typeMapper.mapType(column.type)} GENERATED ALWAYS AS (${column.computedExpression}) STORED`;
  }

  protected renderScalarColumn(column: Omit<ColumnMetadata, 'propertyName'>): string {
    const mappedType = this.typeMapper.mapType(column.type);
    const notNullSql = column.nullable ? '' : ' NOT NULL';
    const defaultSql = this.renderDefault(column);

    // Auto-generated columns (identity). Prefer identity syntax over SERIAL; only when the caller
    // did not specify an explicit default.
    if (column.isGenerated && !defaultSql) {
      if (mappedType === 'INTEGER') {
        return `${this.quoteIdentifier(column.columnName)} INTEGER GENERATED BY DEFAULT AS IDENTITY${notNullSql}`;
      }
      this.logger?.warn(
        `Postgres: isGenerated is only supported for INTEGER identity columns; ignoring for ${column.columnName}`
      );
    }

    return `${this.quoteIdentifier(column.columnName)} ${mappedType}${notNullSql}${defaultSql}`;
  }

  protected renderAlterColumnType(columnName: string, mappedType: string): string {
    return `ALTER COLUMN ${this.quoteIdentifier(columnName)} TYPE ${mappedType}`;
  }

  protected renderDropUniqueConstraint(name: string): string {
    return `DROP CONSTRAINT IF EXISTS ${this.quoteIdentifier(name)}`;
  }

  protected renderTableComment(tableName: string, comment: string): string {
    return `COMMENT ON TABLE ${this.quoteIdentifier(tableName)} IS ${this.quoteStringLiteral(comment)}`;
  }

  protected renderColumnComment(tableName: string, column: ColumnMetadata): string {
    return `COMMENT ON COLUMN ${this.quoteIdentifier(tableName)}.${this.quoteIdentifier(column.columnName)} IS ${this.quoteStringLiteral(column.comment as string)}`;
  }
}
