import type { ColumnMetadata, EntityMetadata } from '@ts-linq/types';
import { SqlHelper } from '@ts-linq/core';
type LoggerLike = { warn(message: string, error?: unknown): void };
import type { PgIndexSpec } from './builders/PgIndexBuilder';
import { PgIndexBuilder } from './builders/PgIndexBuilder';

export class PostgresDdlStrategy {
  private readonly indexBuilder: PgIndexBuilder;

  constructor(private readonly logger?: LoggerLike) {
    this.indexBuilder = new PgIndexBuilder(logger);
  }
  public generateCreateTableSql(entityMetadata: EntityMetadata): string {
    const columnSqls = entityMetadata.columns.map((column: ColumnMetadata) => {
      if (column.isComputed && column.computedExpression) {
        // PostgreSQL supports only STORED
        const storage = (column as { computedStorage?: 'VIRTUAL' | 'STORED' | 'PERSISTED' })
          .computedStorage;
        if (storage && storage !== 'STORED') {
          this.logger?.warn(
            `Postgres: computedStorage='${storage}' is not supported; coercing to STORED for ${column.columnName}`
          );
        }
        return `"${column.columnName}" ${this.mapTypeToPg(column.type)} GENERATED ALWAYS AS (${column.computedExpression}) STORED`;
      }
      const mappedType = this.mapTypeToPg(column.type);
      const notNullSql = column.nullable ? '' : ' NOT NULL';

      let defaultSql = '';
      if (column.defaultExpression) {
        defaultSql = ` DEFAULT ${column.defaultExpression}`;
      } else if (column.defaultValue !== undefined) {
        defaultSql = ` DEFAULT ${SqlHelper.formatValue(column.defaultValue)}`;
      }

      // Auto-generated columns (identity / serial). Prefer identity syntax over SERIAL.
      // Only apply when caller didn't specify an explicit default.
      if (column.isGenerated && !defaultSql) {
        if (mappedType === 'INTEGER') {
          return `"${column.columnName}" INTEGER GENERATED BY DEFAULT AS IDENTITY${notNullSql}`;
        }
        this.logger?.warn(
          `Postgres: isGenerated is only supported for INTEGER identity columns; ignoring for ${column.columnName}`
        );
      }

      return `"${column.columnName}" ${mappedType}${notNullSql}${defaultSql}`;
    });
    if (entityMetadata.primaryKeys && entityMetadata.primaryKeys.length > 0) {
      const primaryKeySql = entityMetadata.primaryKeys
        .map(
          (primaryKey) =>
            `"${entityMetadata.columns.find((column) => column.propertyName === primaryKey)?.columnName || primaryKey}"`
        )
        .join(', ');
      columnSqls.push(`PRIMARY KEY (${primaryKeySql})`);
    }
    return `CREATE TABLE IF NOT EXISTS "${entityMetadata.tableName}" (${columnSqls.join(', ')})`;
  }

  public generateCreateIndexSql(
    table: string,
    index: {
      name: string;
      columns: string[];
      unique: boolean;
      where?: string;
      orders?: { [column: string]: 'ASC' | 'DESC' };
      expressions?: string[];
      collations?: { [column: string]: string };
      nulls?: { [column: string]: 'FIRST' | 'LAST' };
      using?: 'btree' | 'hash' | 'gin' | 'gist';
      concurrently?: boolean;
      withParams?: Record<string, string | number | boolean>;
    }
  ): string {
    return this.indexBuilder.buildCreateIndexSql(table, index as PgIndexSpec);
  }

  public generateAddColumnSql(tableName: string, column: ColumnMetadata): string {
    const mappedType = this.mapTypeToPg(column.type);
    const notNullSql = column.nullable ? '' : ' NOT NULL';
    let defaultSql = '';
    if (column.defaultExpression) {
      defaultSql = ` DEFAULT ${column.defaultExpression}`;
    } else if (column.defaultValue !== undefined) {
      defaultSql = ` DEFAULT ${SqlHelper.formatValue(column.defaultValue)}`;
    }
    return `ALTER TABLE "${tableName}" ADD COLUMN "${column.columnName}" ${mappedType}${notNullSql}${defaultSql}`;
  }

  public generateDropColumnSql(tableName: string, columnName: string): string {
    return `ALTER TABLE "${tableName}" DROP COLUMN "${columnName}"`;
  }

  public generateAlterColumnTypeSql(
    tableName: string,
    columnName: string,
    newType: string
  ): string {
    const mappedType = this.mapTypeToPg(newType);
    return `ALTER TABLE "${tableName}" ALTER COLUMN "${columnName}" TYPE ${mappedType}`;
  }

  public generateRenameTableSql(tableName: string, newTableName: string): string {
    return `ALTER TABLE "${tableName}" RENAME TO "${newTableName}"`;
  }

  public generateForeignKeySql(
    tableName: string,
    fk: {
      name: string;
      columnName: string;
      relatedTableName: string;
      relatedColumnName: string;
      onDelete?: string;
      onUpdate?: string;
    }
  ): string {
    let sql = `ALTER TABLE "${tableName}" ADD CONSTRAINT "${fk.name}" FOREIGN KEY ("${fk.columnName}") REFERENCES "${fk.relatedTableName}" ("${fk.relatedColumnName}")`;
    if (fk.onDelete && fk.onDelete !== 'NO ACTION') {
      sql += ` ON DELETE ${fk.onDelete}`;
    }
    if (fk.onUpdate && fk.onUpdate !== 'NO ACTION') {
      sql += ` ON UPDATE ${fk.onUpdate}`;
    }
    return sql;
  }

  // index helpers relocated to PgIndexBuilder

  public mapTypeToPg(type: string): string {
    const key = (type || '').toUpperCase();
    const map: Record<string, string> = {
      TEXT: 'TEXT',
      STRING: 'TEXT',
      INTEGER: 'INTEGER',
      NUMBER: 'INTEGER',
      REAL: 'DOUBLE PRECISION',
      FLOAT: 'DOUBLE PRECISION',
      DOUBLE: 'DOUBLE PRECISION',
      BOOLEAN: 'BOOLEAN',
      DATETIME: 'TIMESTAMPTZ',
      DATE: 'TIMESTAMPTZ',
      BLOB: 'BYTEA',
      UUID: 'UUID',
      JSONB: 'JSONB',
      JSON: 'JSON'
    };
    return map[key] ?? 'TEXT';
  }
}
