import 'reflect-metadata';

/**
 * Core types and metadata contracts used across the ORM.
 */
export enum EntityState {
    Unchanged = 'unchanged',
    Added = 'added',
    Modified = 'modified',
    Deleted = 'deleted'
}

/**
 * Strategy for loading related entities.
 * - Lazy: relationships are not auto-loaded
 * - Eager: relationships are loaded immediately
 */
export enum LoadingStrategy {
    Lazy = 'lazy',
    Eager = 'eager'
}

/**
 * SQL join types supported by the query builder.
 */
export enum JoinType {
    Inner = 'INNER',
    Left = 'LEFT',
    Right = 'RIGHT',
    Full = 'FULL'
}

/**
 * Internal structure representing a tracked entity and its state.
 */
export interface TrackedEntity {
    entity: any;
    entityClass: Function;
    state: EntityState;
    originalValues?: any;
}

/**
 * Options for constructing a database context.
 */
export interface DbContextOptions {
    /** Provider-specific connection string (e.g., file path for SQLite). */
    connectionString: string;
    /** Database provider key; currently supported: 'sqlite', 'postgresql', 'mssql'. */
    provider?: 'sqlite' | 'mysql' | 'postgresql' | 'mssql';
    /** Optional performance tuning options. */
    performance?: PerformanceOptions;
    /** Optional SQL logger for diagnostics. */
    logger?: SqlLogger;
    /** Optional default loading behavior. */
    loading?: LoadingDefaults;
    /** Optional middleware pipeline for cross-cutting concerns. */
    middlewares?: OrmMiddleware[];
}

/**
 * Options for controlling entity loading behavior.
 */
export interface LoadingOptions {
    /** Default strategy: lazy (no automatic includes) or eager (auto include). */
    strategy?: LoadingStrategy;
    /** Property names of relationships to include (validated against metadata). */
    includes?: string[];
    /** Max recursion depth for nested includes (1 by default). */
    depth?: number;
}

/**
 * Column configuration stored in entity metadata.
 */
export interface ColumnMetadata {
    /** Entity property name. */
    propertyName: string;
    /** Database column name. */
    columnName: string;
    /** Logical column type (TEXT/INTEGER/NUMBER/BOOLEAN/DATETIME/DATE/REAL/BLOB). */
    type: string;
    /** Whether NULL is allowed. */
    nullable: boolean;
    /** Default value applied on INSERT when undefined. */
    defaultValue?: any;
    /** Max length for text columns. */
    length?: number;
    /** Numeric precision for decimals. */
    precision?: number;
    /** Numeric scale for decimals. */
    scale?: number;
    /** True when value is generated by the DB (e.g., AUTOINCREMENT). */
    isGenerated?: boolean;
    /** True when column is an optimistic concurrency token (version). */
    isVersion?: boolean;
}

/**
 * Relationship configuration stored in entity metadata.
 */
export interface RelationshipMetadata {
    /** Navigation property name on the source entity. */
    propertyName: string;
    /** Relationship cardinality. */
    type: 'one-to-many' | 'many-to-one' | 'one-to-one' | 'many-to-many';
    /** Target entity constructor or lazy thunk returning it. */
    targetEntity: Function | (() => Function);
    /** Foreign key column name on the dependent side (optional). */
    foreignKey?: string;
    /** Inverse navigation property name on the target entity (optional). */
    inverseSide?: string;
    /** Cascade operations (insert/update/delete) when true. */
    cascade?: boolean;
}

/**
 * Index definition for an entity.
 */
export interface IndexMetadata {
    /** Index identifier (unique within table). */
    name: string;
    /** Ordered list of column names participating in the index. */
    columns: string[];
    /** Whether the index enforces uniqueness. */
    unique: boolean;
}

/**
 * Full metadata description for an entity type.
 */
export interface EntityMetadata {
    /** Entity constructor function. */
    target: Function;
    /** Physical table name. */
    tableName: string;
    /** All mapped columns. */
    columns: ColumnMetadata[];
    /** Property names forming the primary key (composite supported). */
    primaryKeys: string[];
    /** Declared relationships. */
    relationships: RelationshipMetadata[];
    /** Index definitions. */
    indexes: IndexMetadata[];
}

/**
 * Standardized structure for returning query results with optional paging info.
 */
export interface QueryResult<T> {
    /** Result rows. */
    data: T[];
    /** Optional total for paged queries. */
    total?: number;
    /** 1-based page number. */
    page?: number;
    /** Page size. */
    pageSize?: number;
}

/**
 * Generic key-value map for aggregate query results.
 */
export interface AggregateResult {
    [key: string]: any;
}

/**
 * Join clause used during SQL generation.
 */
export interface JoinClause {
    /** SQL join type keyword. */
    type: JoinType;
    /** Joined table name (or subquery alias). */
    table: string;
    /** ON clause (already escaped/mapped as needed). */
    on: string;
    /** Optional table alias. */
    alias?: string;
}

/**
 * WHERE clause fragment with parameter list.
 */
export interface WhereClause {
    /** SQL condition fragment with placeholders (e.g., "price > ?"). */
    condition: string;
    /** Positional parameter values to bind. */
    parameters: any[];
}

/**
 * ORDER BY clause element.
 */
export interface OrderByClause {
    /** Column/expression to order by. */
    column: string;
    /** ASC or DESC. */
    direction: 'ASC' | 'DESC';
}

/**
 * GROUP BY configuration and optional HAVING condition.
 */
export interface GroupByClause {
    /** Column list used for grouping. */
    columns: string[];
    /** Optional HAVING predicate. */
    having?: WhereClause;
}

/**
 * Accumulated options that define a SQL query to be generated.
 */
export interface QueryOptions {
    /** Selected columns or expressions (defaults to *). */
    select?: string[];
    /** WHERE predicates with parameters. */
    where?: WhereClause[];
    /** ORDER BY items. */
    orderBy?: OrderByClause[];
    /** GROUP BY clause with optional HAVING. */
    groupBy?: GroupByClause;
    /** JOIN clauses (reserved for future use). */
    joins?: JoinClause[];
    /** LIMIT value. */
    limit?: number;
    /** OFFSET value. */
    offset?: number;
    /** DISTINCT selector. */
    distinct?: boolean;
}

/**
 * Performance-related options to tune caching and counts.
 */
export interface PerformanceOptions {
    /** Enable level-2 entity cache (by primary key). Default: false. */
    enableEntityCache?: boolean;
    /** Maximum L2 cache size. Default: 10000. */
    entityCacheSize?: number;
    /** Enable count() result caching for pagination. Default: false. */
    enableCountCache?: boolean;
    /** TTL for count() cache entries in milliseconds. Default: 0 (no TTL, disabled unless enableCountCache). */
    countCacheTtlMs?: number;
}

/**
 * Default loading settings configured at the context level.
 */
export interface LoadingDefaults {
    /** Default loading strategy for find/findAll and include population. */
    strategy?: LoadingStrategy;
    /** Default recursion depth for relationship loading (default: 1). */
    depth?: number;
}

/**
 * Minimal SQL logger interface for centralized diagnostics.
 */
export interface SqlLogger {
    /** Called right before a query is executed. */
    queryStart?(info: { sql: string; params: any[]; traceId?: string }): void;
    /** Called right after a query is executed. */
    queryEnd?(info: { sql: string; params: any[]; durationMs: number; traceId?: string; rows?: number; error?: Error }): void;
}

/** Middleware hooks for cross-cutting concerns (tracing, metrics, etc.). */
export interface OrmMiddleware {
    beforeExecute?(info: { sql: string; params: any[]; traceId?: string }): void | Promise<void>;
    afterExecute?(info: { sql: string; params: any[]; durationMs: number; traceId?: string; rows?: number; error?: Error }): void | Promise<void>;
    entityMaterialized?(info: { entity: any; metadata?: EntityMetadata }): void | Promise<void>;
}

/**
 * Result type for non-exceptional control flow.
 */
export type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E };
/** Create a successful Result. */
export const ok = <T>(value: T): Result<T, never> => ({ ok: true, value });
/** Create a failed Result. */
export const err = <E>(error: E): Result<never, E> => ({ ok: false, error });

/** Generic database error with optional engine-specific code. */
export class DatabaseError extends Error {
    public code?: string;
    constructor(message: string, code?: string) {
        super(message);
        this.name = 'DatabaseError';
        this.code = code;
    }
}

/** Unique constraint violation error. */
export class UniqueConstraintError extends DatabaseError {
    constructor(message: string, code?: string) {
        super(message, code);
        this.name = 'UniqueConstraintError';
    }
}

/** Foreign key constraint violation error. */
export class ForeignKeyConstraintError extends DatabaseError {
    constructor(message: string, code?: string) {
        super(message, code);
        this.name = 'ForeignKeyConstraintError';
    }
}

/** Validation error for model constraints before persistence. */
export class ValidationError extends Error {
    public details?: Array<{ entity: string; property: string; message: string }>;
    constructor(message: string, details?: Array<{ entity: string; property: string; message: string }>) {
        super(message);
        this.name = 'ValidationError';
        this.details = details;
    }
}

/** Optimistic concurrency violation error. */
export class OptimisticConcurrencyError extends DatabaseError {
    constructor(message: string = 'Optimistic concurrency check failed', code?: string) {
        super(message, code);
        this.name = 'OptimisticConcurrencyError';
    }
}
