/**
 * Unit tests for Queryable.executeUpdate() and Queryable.executeDelete() (P0-04).
 *
 * Verifies:
 * - SQL generated by TestDialect is correct for UPDATE / DELETE
 * - WHERE clauses flow through correctly
 * - setProperty supports literal values, JS-computed values, and column references
 * - include() before executeUpdate/executeDelete throws a descriptive error
 * - Empty setters throws
 * - provider.executeNonQuery is called with the correct SQL and parameters
 */
import 'reflect-metadata';

import { describe, expect, it, jest } from '@jest/globals';
import { DatabaseProvider } from '@ts-linq/core';
import { MetadataStorage } from '@ts-linq/metadata';
import type {
  BulkDeleteContext,
  BulkUpdateContext,
  SqlDialect,
  SqlParameter,
  SqlWithParams
} from '@ts-linq/types';

import { Queryable } from '../src/Queryable';

// ── Entity fixture ────────────────────────────────────────────────────────────

class User {
  id!: number;
  name!: string;
  isLocked!: boolean;
  loginCount!: number;
  displayName!: string;
}

// ── TestDialect (bulk DML capable) ───────────────────────────────────────────

class BulkTestDialect implements SqlDialect {
  public buildSelect(
    entityClass: new () => unknown,
    _options: unknown
  ): { query: string; parameters: SqlParameter[] } {
    const meta = MetadataStorage.getEntity(entityClass) ?? { tableName: 'unknown' };
    return { query: `SELECT * FROM ${meta.tableName}`, parameters: [] };
  }

  public quoteIdentifier(identifier: string): string {
    return `"${identifier}"`;
  }

  public buildBulkUpdate(ctx: BulkUpdateContext): SqlWithParams {
    const params: SqlParameter[] = [];
    const setClauses: string[] = [];
    for (const setter of ctx.setters) {
      if (setter.value.kind === 'literal') {
        setClauses.push(`"${setter.columnName}" = ?`);
        params.push(...setter.value.params);
      } else {
        setClauses.push(`"${setter.columnName}" = "${setter.value.refColumnName}"`);
      }
    }
    let sql = `UPDATE "${ctx.tableName}" SET ${setClauses.join(', ')}`;
    if (ctx.where.length > 0) {
      const conditions = ctx.where.map((w) => w.condition).join(' AND ');
      for (const w of ctx.where) params.push(...w.parameters);
      sql += ` WHERE ${conditions}`;
    }
    return { sql, parameters: params };
  }

  public buildBulkDelete(ctx: BulkDeleteContext): SqlWithParams {
    const params: SqlParameter[] = [];
    let sql = `DELETE FROM "${ctx.tableName}"`;
    if (ctx.where.length > 0) {
      const conditions = ctx.where.map((w) => w.condition).join(' AND ');
      for (const w of ctx.where) params.push(...w.parameters);
      sql += ` WHERE ${conditions}`;
    }
    return { sql, parameters: params };
  }
}

// ── TestProvider ──────────────────────────────────────────────────────────────

class BulkTestProvider extends DatabaseProvider {
  private readonly _dialect = new BulkTestDialect();
  public lastNonQuerySql = '';
  public lastNonQueryParams: readonly SqlParameter[] = [];

  constructor() {
    super(
      'bulk-test://',
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined
    );
    (this as unknown as { providerName: string }).providerName = 'bulk-test';
  }

  public override async connect(): Promise<void> {}
  public override async disconnect(): Promise<void> {}
  public async createTable(): Promise<void> {}
  public getDialect(): SqlDialect {
    return this._dialect;
  }
  public async insert<T extends object>(e: T): Promise<T> {
    return e;
  }
  public async update<T extends object>(e: T): Promise<T> {
    return e;
  }
  public async delete(): Promise<void> {}
  public async findById<T extends object>(): Promise<T | null> {
    return null;
  }
  public async findAll<T extends object>(): Promise<T[]> {
    return [];
  }
  public async findWhere<T extends object>(): Promise<T[]> {
    return [];
  }
  public async findWhereIn<T extends object>(): Promise<T[]> {
    return [];
  }

  protected async doExecuteQuery<T>(): Promise<T[]> {
    return [];
  }

  protected async doExecuteNonQuery(sql: string, params: readonly SqlParameter[]): Promise<number> {
    this.lastNonQuerySql = sql;
    this.lastNonQueryParams = params;
    return 42;
  }

  public override async beginTransaction(): Promise<void> {}
  public override async commitTransaction(): Promise<void> {}
  public override async rollbackTransaction(): Promise<void> {}
  protected override async doConnect(): Promise<void> {}
  protected override async doDisconnect(): Promise<void> {}
  protected override async doBeginTransaction(): Promise<void> {}
  protected override async doCommitTransaction(): Promise<void> {}
  protected override async doRollbackTransaction(): Promise<void> {}
}

// ── Metadata setup ────────────────────────────────────────────────────────────

function registerUserMetadata(): void {
  MetadataStorage.getInstance().clear();
  MetadataStorage.addEntity(User, 'users');
  MetadataStorage.addColumn(User, {
    propertyName: 'id',
    columnName: 'id',
    type: 'INTEGER',
    primaryKey: true
  });
  MetadataStorage.addPrimaryKey(User, 'id');
  MetadataStorage.addColumn(User, { propertyName: 'name', columnName: 'name', type: 'TEXT' });
  MetadataStorage.addColumn(User, {
    propertyName: 'isLocked',
    columnName: 'is_locked',
    type: 'BOOLEAN'
  });
  MetadataStorage.addColumn(User, {
    propertyName: 'loginCount',
    columnName: 'login_count',
    type: 'INTEGER'
  });
  MetadataStorage.addColumn(User, {
    propertyName: 'displayName',
    columnName: 'display_name',
    type: 'TEXT'
  });
}

function makeQueryable(provider: BulkTestProvider): Queryable<User> {
  return new Queryable<User>(User, provider);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('Queryable.executeDelete() (P0-04)', () => {
  beforeEach(() => {
    registerUserMetadata();
  });

  it('emits DELETE FROM without WHERE when no where() called', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    const rows = await q.executeDelete();

    expect(rows).toBe(42);
    expect(provider.lastNonQuerySql).toBe('DELETE FROM "users"');
    expect(provider.lastNonQueryParams).toEqual([]);
  });

  it('emits DELETE FROM with WHERE clause when where() is applied', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    // Simulate a WHERE clause by calling whereCompiled directly
    q.whereCompiled({
      ast: {
        type: 'binary',
        operator: '==',
        left: { type: 'property', name: 'isLocked' },
        right: { type: 'literal', value: true }
      },
      parameters: []
    });

    await q.executeDelete();

    expect(provider.lastNonQuerySql).toContain('DELETE FROM "users"');
    expect(provider.lastNonQuerySql).toContain('WHERE');
  });

  it('throws when include() was called before executeDelete()', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    // Manually push to _includes to simulate include() having been called
    (q as unknown as { _includes: string[] })._includes.push('posts');

    await expect(q.executeDelete()).rejects.toThrow(
      /Cannot call executeDelete\(\) after include\(\)/
    );
  });

  it('returns the rowsAffected count from the provider', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    const count = await q.executeDelete();

    expect(count).toBe(42);
  });
});

describe('Queryable.executeUpdate() (P0-04)', () => {
  beforeEach(() => {
    registerUserMetadata();
  });

  it('emits UPDATE SET with a literal value (no WHERE)', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    await q.executeUpdate((s) => s.setProperty((u) => u.name, 'Locked'));

    expect(provider.lastNonQuerySql).toBe('UPDATE "users" SET "name" = ?');
    expect(provider.lastNonQueryParams).toEqual(['Locked']);
  });

  it('emits UPDATE SET with a boolean literal', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    await q.executeUpdate((s) => s.setProperty((u) => u.isLocked, true));

    expect(provider.lastNonQuerySql).toBe('UPDATE "users" SET "is_locked" = ?');
    expect(provider.lastNonQueryParams).toEqual([true]);
  });

  it('supports a JS-precomputed (computed) value as a literal', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);
    const currentCount = 5;

    await q.executeUpdate((s) => s.setProperty((u) => u.loginCount, currentCount + 1));

    expect(provider.lastNonQuerySql).toBe('UPDATE "users" SET "login_count" = ?');
    expect(provider.lastNonQueryParams).toEqual([6]);
  });

  it('supports column reference (copies one column to another)', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    await q.executeUpdate((s) =>
      s.setProperty(
        (u) => u.name,
        (u) => u.displayName
      )
    );

    expect(provider.lastNonQuerySql).toBe('UPDATE "users" SET "name" = "display_name"');
    expect(provider.lastNonQueryParams).toEqual([]);
  });

  it('supports chaining multiple setProperty() calls', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    await q.executeUpdate((s) =>
      s.setProperty((u) => u.name, 'Locked User').setProperty((u) => u.isLocked, true)
    );

    expect(provider.lastNonQuerySql).toBe('UPDATE "users" SET "name" = ?, "is_locked" = ?');
    expect(provider.lastNonQueryParams).toEqual(['Locked User', true]);
  });

  it('includes WHERE clause in the UPDATE when where() is applied', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    q.whereCompiled({
      ast: {
        type: 'binary',
        operator: '==',
        left: { type: 'property', name: 'id' },
        right: { type: 'literal', value: 1 }
      },
      parameters: []
    });

    await q.executeUpdate((s) => s.setProperty((u) => u.name, 'Admin'));

    expect(provider.lastNonQuerySql).toContain('WHERE');
    expect(provider.lastNonQuerySql).toContain('UPDATE "users" SET "name" = ?');
  });

  it('throws when include() was called before executeUpdate()', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    (q as unknown as { _includes: string[] })._includes.push('posts');

    await expect(q.executeUpdate((s) => s.setProperty((u) => u.name, 'Test'))).rejects.toThrow(
      /Cannot call executeUpdate\(\) after include\(\)/
    );
  });

  it('throws when no setProperty() calls are provided', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    await expect(q.executeUpdate((s) => s)).rejects.toThrow(/at least one setProperty/);
  });

  it('throws when property name does not exist in metadata', async () => {
    const provider = new BulkTestProvider();
    // Cast to Queryable<any> to bypass compile-time type safety for this error-path test
    const q = makeQueryable(provider) as unknown as Queryable<{ nonexistent: string }>;

    await expect(
      q.executeUpdate((s) => s.setProperty((u) => u.nonexistent, 'value'))
    ).rejects.toThrow(/no column mapping found/);
  });

  it('returns the rowsAffected count from the provider', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);

    const count = await q.executeUpdate((s) => s.setProperty((u) => u.name, 'Test'));

    expect(count).toBe(42);
  });

  it('spy on executeNonQuery confirms it is called once', async () => {
    const provider = new BulkTestProvider();
    const q = makeQueryable(provider);
    const spy = jest.spyOn(provider, 'executeNonQuery');

    await q.executeUpdate((s) => s.setProperty((u) => u.isLocked, false));

    expect(spy).toHaveBeenCalledTimes(1);
  });
});
