import 'reflect-metadata';
import { MetadataStorage } from '../metadata/MetadataStorage';
import { ColumnMetadata } from '../types';

/**
 * Options for configuring a column mapping on an entity property.
 *
 * - name: Optional explicit column name. Defaults to the property name.
 * - type: Database column type. If omitted, it is inferred from the property TS design type.
 * - nullable: Whether the column accepts NULL. Defaults to true unless explicitly set to false.
 * - defaultValue: Default value used when inserting rows.
 * - length: Length constraint for text-like types.
 * - precision: Numeric precision for decimal types.
 * - scale: Numeric scale for decimal types.
 * - generated: Marks the column as generated by the database (e.g., identity/auto-increment).
 */
export interface ColumnOptions {
    name?: string;
    type?: string;
    nullable?: boolean;
    defaultValue?: any;
    length?: number;
    precision?: number;
    scale?: number;
    generated?: boolean;
    /** Marks this column as an optimistic concurrency token (version). */
    version?: boolean;
}

/**
 * Property decorator that registers column metadata for the target entity property.
 *
 * If the `type` is not provided, it will be inferred from the TypeScript design type
 * via `reflect-metadata` and mapped to a reasonable SQL type.
 *
 * @param options Column configuration options.
 * @returns A property decorator that records column metadata.
 */
export function Column(options: ColumnOptions = {}): PropertyDecorator {
    return function (target: any, propertyKey: string | symbol) {
        const propertyName = propertyKey.toString();
        
        // Get the design type using reflect-metadata
        const designType = Reflect.getMetadata('design:type', target, propertyKey);
        
        const columnMetadata: ColumnMetadata = {
            propertyName,
            columnName: options?.name || propertyName,
            type: options?.type || getTypeString(designType),
            nullable: options?.nullable !== false,
            defaultValue: options?.defaultValue,
            length: options?.length,
            precision: options?.precision,
            scale: options?.scale,
            isGenerated: options?.generated || false,
            isVersion: options?.version || false
        };

        MetadataStorage.addColumn(target.constructor, columnMetadata);

        // Persist on constructor to support rehydration
        const ctor = target.constructor;
        const existing: ColumnMetadata[] = Reflect.getOwnMetadata('orm:columns', ctor) || [];
        existing.push(columnMetadata);
        Reflect.defineMetadata('orm:columns', existing, ctor);
    };
}

/**
 * Map a JavaScript/TypeScript runtime constructor to a default SQL type.
 *
 * @param type The runtime constructor captured by `reflect-metadata` (e.g., String, Number).
 * @returns A string representing the SQL type to use.
 */
function getTypeString(type: any): string {
    if (!type) return 'TEXT';
    
    switch (type.name) {
        case 'String':
            return 'TEXT';
        case 'Number':
            return 'INTEGER';
        case 'Boolean':
            return 'BOOLEAN';
        case 'Date':
            return 'DATETIME';
        case 'Array':
            return 'TEXT'; // Store as JSON
        case 'Object':
            return 'TEXT'; // Store as JSON
        default:
            return 'TEXT';
    }
}
