import type { Dialect } from '../Dialect';
import { buildEnsureMigrationsTableSql, MIGRATIONS_TABLE } from '../runner/MigrationsTableSchema';

/**
 * Metadata and SQL for a single migration step consumed by `IdempotentEmitter`.
 * Distinct from `MigrationStep` in `DiffMigrationGenerator` which only carries raw SQL.
 */
export interface IdempotentMigrationStep {
  /** Sortable version identifier (e.g. `20241201000000`). */
  version: string;
  /** Human-readable name (e.g. `CreateUsers`). */
  name: string;
  /** UP SQL statements to execute for this migration. */
  upSql: string[];
}

/**
 * Emits idempotent SQL from an ordered list of migration steps.
 *
 * Each migration step is wrapped in a dialect-specific guard block that checks
 * `__migrations` before executing, making the script safe to re-run.
 * The history record is inserted inside the same guard so it is only written
 * when the migration is actually applied.
 *
 * Mirrors the behaviour of `dotnet ef migrations script --idempotent`.
 *
 * ### Programmatic execution
 *
 * Use `emitStatements()` when feeding SQL to a database driver, since drivers
 * do not support client-side commands (`GO`, `DELIMITER`, etc.).
 * Use `emit()` only for writing `.sql` files intended for CLI tools.
 *
 * @example
 * // Write to file (CLI tools handle multi-statement SQL)
 * fs.writeFileSync('migrate.sql', emitter.emit(steps, 'postgresql'));
 *
 * // Execute programmatically via a database driver
 * for (const stmt of emitter.emitStatements(steps, 'mysql')) {
 *   await provider.executeNonQuery(stmt);
 * }
 */
export class IdempotentEmitter {
  /** Shared with the runner's history store (single source of truth). */
  private static readonly MIGRATIONS_TABLE = MIGRATIONS_TABLE;

  /**
   * Produce a complete idempotent SQL script as a single string.
   *
   * For PostgreSQL and SQL Server the result is suitable for direct
   * programmatic execution.
   * For MySQL the result is a file-oriented script — use `emitStatements()`
   * when executing via the `mysql2` driver.
   *
   * @param steps  Ordered list of migrations (caller must sort by version).
   * @param dialect  Target database dialect.
   */
  public emit(steps: IdempotentMigrationStep[], dialect: Dialect): string {
    return this.emitStatements(steps, dialect).join('\n\n');
  }

  /**
   * Produce an array of individually-executable SQL statements.
   *
   * Each element may be sent to the database driver via a single
   * `executeNonQuery()` call. This avoids issues with batch separators
   * (`GO` for SQL Server) and client-only commands (`DELIMITER` for MySQL)
   * that are not understood by programmatic database drivers.
   *
   * @param steps  Ordered list of migrations (caller must sort by version).
   * @param dialect  Target database dialect.
   */
  public emitStatements(steps: IdempotentMigrationStep[], dialect: Dialect): string[] {
    const header = this.buildHeader(dialect);
    const blocks = steps.flatMap((step) => this.buildStatements(step, dialect));
    return [header, ...blocks];
  }

  // ---------------------------------------------------------------------------
  // Header: ensure __migrations table exists (one executable statement)
  // ---------------------------------------------------------------------------

  private buildHeader(dialect: Dialect): string {
    switch (dialect) {
      case 'postgresql':
        return this.pgEnsureTable();
      case 'mssql':
        return this.mssqlEnsureTable();
      case 'mysql':
        return this.mysqlEnsureTable();
    }
  }

  private pgEnsureTable(): string {
    return [
      '-- Idempotent migration script (PostgreSQL)',
      '-- Generated by @ts-linq/migrations',
      '',
      `${buildEnsureMigrationsTableSql('postgresql').trim()};`
    ].join('\n');
  }

  /**
   * SQL Server: use IF NOT EXISTS guard — no GO separator.
   * GO is a SQL Server Management Studio batch separator; it is not understood
   * by programmatic drivers (mssql / tedious).
   */
  private mssqlEnsureTable(): string {
    return [
      '-- Idempotent migration script (SQL Server)',
      '-- Generated by @ts-linq/migrations',
      '',
      buildEnsureMigrationsTableSql('mssql').trim()
    ].join('\n');
  }

  private mysqlEnsureTable(): string {
    return [
      '-- Idempotent migration script (MySQL)',
      '-- Generated by @ts-linq/migrations',
      '',
      `${buildEnsureMigrationsTableSql('mysql').trim()};`
    ].join('\n');
  }

  // ---------------------------------------------------------------------------
  // Per-migration guard blocks — returns one or more executable statements
  // ---------------------------------------------------------------------------

  private buildStatements(step: IdempotentMigrationStep, dialect: Dialect): string[] {
    switch (dialect) {
      case 'postgresql':
        return [this.pgBlock(step)];
      case 'mssql':
        return [this.mssqlBlock(step)];
      case 'mysql':
        return this.mysqlStatements(step);
    }
  }

  /**
   * PostgreSQL: one PL/pgSQL anonymous block per migration.
   * DDL is fully supported inside DO $$ … $$ blocks.
   * PL/pgSQL requires every statement inside a block to be terminated with `;`.
   */
  private pgBlock(step: IdempotentMigrationStep): string {
    const stmts = step.upSql
      .map((s) => this.ensureSemicolon(this.indentSql(s, '        ')))
      .join('\n\n');
    const insertRecord = [
      `        INSERT INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `        VALUES ('${step.version}', '${step.name}', NOW()::TEXT);`
    ].join('\n');

    return [
      `-- Migration: ${step.version}_${step.name}`,
      `DO $migration$`,
      `BEGIN`,
      `    IF NOT EXISTS (`,
      `        SELECT 1 FROM ${IdempotentEmitter.MIGRATIONS_TABLE}`,
      `        WHERE version = '${step.version}'`,
      `    ) THEN`,
      stmts,
      '',
      insertRecord,
      `    END IF;`,
      `END $migration$;`
    ].join('\n');
  }

  /**
   * SQL Server (T-SQL): IF NOT EXISTS / BEGIN...END block per migration.
   * GO is intentionally omitted — programmatic drivers do not support it.
   */
  private mssqlBlock(step: IdempotentMigrationStep): string {
    const stmts = step.upSql.map((s) => this.indentSql(s, '    ')).join('\n\n');
    const insertRecord = [
      `    INSERT INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `    VALUES ('${step.version}', '${step.name}', CONVERT(VARCHAR(50), GETDATE(), 126))`
    ].join('\n');

    return [
      `-- Migration: ${step.version}_${step.name}`,
      `IF NOT EXISTS (`,
      `    SELECT 1 FROM ${IdempotentEmitter.MIGRATIONS_TABLE}`,
      `    WHERE version = '${step.version}'`,
      `)`,
      `BEGIN`,
      stmts,
      '',
      insertRecord,
      `END`
    ].join('\n');
  }

  /**
   * MySQL: returns multiple individually-executable statements per migration.
   *
   * MySQL does not support IF…THEN blocks outside stored procedures, and the
   * `DELIMITER` command is a MySQL *client* directive that is NOT sent to the
   * server — it is therefore unavailable in programmatic drivers (mysql2).
   *
   * Instead we emit:
   * 1. Each DDL statement as-is (DDL should use `IF NOT EXISTS` variants for idempotency).
   * 2. An `INSERT IGNORE` to record the migration — safe to re-run thanks to the
   *    PRIMARY KEY constraint.
   *
   * Limitation: non-idempotent DDL (e.g. `ALTER TABLE ADD COLUMN` without
   * `IF NOT EXISTS`) will fail on re-runs. Use `IF NOT EXISTS`-aware DDL in
   * migrations targeting MySQL.
   */
  private mysqlStatements(step: IdempotentMigrationStep): string[] {
    const comment = `-- Migration: ${step.version}_${step.name}`;
    const ddlStatements = step.upSql.map((s, i) => {
      const prefix = i === 0 ? `${comment}\n` : '';
      return `${prefix}${s.trim()};`;
    });

    const insertIgnore = [
      `INSERT IGNORE INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `VALUES ('${step.version}', '${step.name}', NOW());`
    ].join('\n');

    return [...ddlStatements, insertIgnore];
  }

  /** Append a semicolon if the statement does not already end with one. */
  private ensureSemicolon(sql: string): string {
    const trimmed = sql.trimEnd();
    return trimmed.endsWith(';') ? trimmed : `${trimmed};`;
  }

  /** Indent every line of a SQL statement consistently. */
  private indentSql(sql: string, indent: string): string {
    return sql
      .trim()
      .split('\n')
      .map((line) => (line.trim() ? `${indent}${line.trim()}` : ''))
      .join('\n');
  }
}
