import type { Dialect } from '../Dialect';

/**
 * Metadata and SQL for a single migration step consumed by `IdempotentEmitter`.
 * Distinct from `MigrationStep` in `DiffMigrationGenerator` which only carries raw SQL.
 */
export interface IdempotentMigrationStep {
  /** Sortable version identifier (e.g. `20241201000000`). */
  version: string;
  /** Human-readable name (e.g. `CreateUsers`). */
  name: string;
  /** UP SQL statements to execute for this migration. */
  upSql: string[];
}

/**
 * Emits a complete idempotent SQL script from an ordered list of migration steps.
 *
 * Each migration step is wrapped in a dialect-specific guard block that checks
 * `__migrations` before executing, making the script safe to re-run.
 * The history record is inserted inside the same guard so it is only written
 * when the migration is actually applied.
 *
 * Mirrors the behaviour of `dotnet ef migrations script --idempotent`.
 *
 * @example
 * const emitter = new IdempotentEmitter();
 * const sql = emitter.emit(steps, 'postgresql');
 * fs.writeFileSync('migrate.sql', sql);
 */
export class IdempotentEmitter {
  private static readonly MIGRATIONS_TABLE = '__migrations';

  /**
   * Produce a complete idempotent SQL script for all provided migration steps.
   *
   * @param steps  Ordered list of migrations (caller must sort by version).
   * @param dialect  Target database dialect.
   * @returns  A single SQL string safe to feed to the database driver or `psql`/`sqlcmd`/`mysql`.
   */
  public emit(steps: IdempotentMigrationStep[], dialect: Dialect): string {
    const header = this.buildHeader(dialect);
    const blocks = steps.map((step) => this.buildBlock(step, dialect));
    return [header, ...blocks].join('\n\n');
  }

  // ---------------------------------------------------------------------------
  // Header: ensure __migrations table exists
  // ---------------------------------------------------------------------------

  private buildHeader(dialect: Dialect): string {
    switch (dialect) {
      case 'postgresql':
        return this.pgEnsureTable();
      case 'mssql':
        return this.mssqlEnsureTable();
      case 'mysql':
        return this.mysqlEnsureTable();
    }
  }

  private pgEnsureTable(): string {
    return [
      '-- Idempotent migration script (PostgreSQL)',
      '-- Generated by @ts-linq/migrations',
      '',
      `CREATE TABLE IF NOT EXISTS ${IdempotentEmitter.MIGRATIONS_TABLE} (`,
      '    version TEXT PRIMARY KEY,',
      '    name TEXT NOT NULL,',
      '    applied_at TEXT NOT NULL',
      ');'
    ].join('\n');
  }

  private mssqlEnsureTable(): string {
    return [
      '-- Idempotent migration script (SQL Server)',
      '-- Generated by @ts-linq/migrations',
      '',
      `IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = '${IdempotentEmitter.MIGRATIONS_TABLE}')`,
      'BEGIN',
      `    CREATE TABLE ${IdempotentEmitter.MIGRATIONS_TABLE} (`,
      '        version NVARCHAR(50) NOT NULL PRIMARY KEY,',
      '        name NVARCHAR(255) NOT NULL,',
      '        applied_at NVARCHAR(50) NOT NULL',
      '    );',
      'END',
      'GO'
    ].join('\n');
  }

  private mysqlEnsureTable(): string {
    return [
      '-- Idempotent migration script (MySQL)',
      '-- Generated by @ts-linq/migrations',
      '',
      `CREATE TABLE IF NOT EXISTS ${IdempotentEmitter.MIGRATIONS_TABLE} (`,
      '    version VARCHAR(50) NOT NULL PRIMARY KEY,',
      '    name VARCHAR(255) NOT NULL,',
      '    applied_at VARCHAR(50) NOT NULL',
      ');'
    ].join('\n');
  }

  // ---------------------------------------------------------------------------
  // Per-migration guard blocks
  // ---------------------------------------------------------------------------

  private buildBlock(step: IdempotentMigrationStep, dialect: Dialect): string {
    switch (dialect) {
      case 'postgresql':
        return this.pgBlock(step);
      case 'mssql':
        return this.mssqlBlock(step);
      case 'mysql':
        return this.mysqlBlock(step);
    }
  }

  /**
   * PostgreSQL: wrap each migration in a PL/pgSQL anonymous block.
   * DDL is fully supported inside DO $$ … $$ blocks in PostgreSQL.
   */
  private pgBlock(step: IdempotentMigrationStep): string {
    const stmts = step.upSql.map((s) => this.indentSql(s, '        ')).join('\n\n');
    const insertRecord = [
      `        INSERT INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `        VALUES ('${step.version}', '${step.name}', NOW()::TEXT);`
    ].join('\n');

    return [
      `-- Migration: ${step.version}_${step.name}`,
      `DO $migration$`,
      `BEGIN`,
      `    IF NOT EXISTS (`,
      `        SELECT 1 FROM ${IdempotentEmitter.MIGRATIONS_TABLE}`,
      `        WHERE version = '${step.version}'`,
      `    ) THEN`,
      stmts,
      '',
      insertRecord,
      `    END IF;`,
      `END $migration$;`
    ].join('\n');
  }

  /**
   * SQL Server (T-SQL): use IF NOT EXISTS / BEGIN...END.
   * Each statement is terminated with a semicolon; a GO batch separator follows.
   */
  private mssqlBlock(step: IdempotentMigrationStep): string {
    const stmts = step.upSql.map((s) => this.indentSql(s, '    ')).join('\n\n');
    const insertRecord = [
      `    INSERT INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `    VALUES ('${step.version}', '${step.name}', CONVERT(VARCHAR(50), GETDATE(), 126));`
    ].join('\n');

    return [
      `-- Migration: ${step.version}_${step.name}`,
      `IF NOT EXISTS (`,
      `    SELECT 1 FROM ${IdempotentEmitter.MIGRATIONS_TABLE}`,
      `    WHERE version = '${step.version}'`,
      `)`,
      `BEGIN`,
      stmts,
      '',
      insertRecord,
      `END`,
      `GO`
    ].join('\n');
  }

  /**
   * MySQL: wrap each migration in a temporary stored procedure.
   * MySQL does not support IF...THEN blocks outside stored procedures.
   */
  private mysqlBlock(step: IdempotentMigrationStep): string {
    const procName = `_apply_migration_${step.version}`;
    const stmts = step.upSql.map((s) => this.indentSql(s, '    ')).join('\n\n');
    const insertRecord = [
      `    INSERT INTO ${IdempotentEmitter.MIGRATIONS_TABLE} (version, name, applied_at)`,
      `    VALUES ('${step.version}', '${step.name}', NOW());`
    ].join('\n');

    return [
      `-- Migration: ${step.version}_${step.name}`,
      `DROP PROCEDURE IF EXISTS ${procName};`,
      `DELIMITER //`,
      `CREATE PROCEDURE ${procName}()`,
      `BEGIN`,
      `    IF NOT EXISTS (`,
      `        SELECT 1 FROM ${IdempotentEmitter.MIGRATIONS_TABLE}`,
      `        WHERE version = '${step.version}'`,
      `    ) THEN`,
      stmts,
      '',
      insertRecord,
      `    END IF;`,
      `END //`,
      `DELIMITER ;`,
      `CALL ${procName}();`,
      `DROP PROCEDURE IF EXISTS ${procName};`
    ].join('\n');
  }

  /** Indent every line of a SQL statement consistently. */
  private indentSql(sql: string, indent: string): string {
    return sql
      .trim()
      .split('\n')
      .map((line) => (line.trim() ? `${indent}${line.trim()}` : ''))
      .join('\n');
  }
}
