import type { DdlStrategyContractGolden } from '@ts-linq/testkits';

/**
 * PostgreSQL golden expectations for the shared DDL contract (task-7). Captured from the current
 * (byte-verified) `PostgresDdlStrategy` output. See `@ts-linq/testkits` `runDdlStrategyContract`.
 */
export const pgGolden: DdlStrategyContractGolden = {
  createTable: {
    simple: `CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT NOT NULL, "age" INTEGER, PRIMARY KEY ("id"))`,
    'composite-pk': `CREATE TABLE IF NOT EXISTS "order_items" ("order_id" INTEGER NOT NULL, "product_id" INTEGER NOT NULL, "quantity" INTEGER NOT NULL, PRIMARY KEY ("order_id", "product_id"))`,
    'computed-check': `CREATE TABLE IF NOT EXISTS "products" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "price" INTEGER NOT NULL, "total" INTEGER GENERATED ALWAYS AS (price * 2) STORED, PRIMARY KEY ("id"), CONSTRAINT "chk_price" CHECK (price > 0))`,
    commented: `CREATE TABLE IF NOT EXISTS "accounts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" TEXT NOT NULL, PRIMARY KEY ("id"))`
  },
  columnDefinition: {
    plain: `"name" TEXT`,
    'not-null-default': `"active" BOOLEAN NOT NULL DEFAULT 1`,
    generated: `"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
    computed: `"total" INTEGER GENERATED ALWAYS AS (a + b) STORED`,
    length: `"code" TEXT`
  },
  createIndex: {
    simple: `CREATE INDEX IF NOT EXISTS "idx_users_name" ON "users" ("name")`,
    unique: `CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email")`
  },
  addColumn: {
    plain: `ALTER TABLE "users" ADD COLUMN "name" TEXT`
  },
  dropColumn: {
    simple: `ALTER TABLE "users" DROP COLUMN "obsolete"`
  },
  alterColumnType: {
    simple: `ALTER TABLE "users" ALTER COLUMN "description" TYPE TEXT`
  },
  renameTable: {
    simple: `ALTER TABLE "old_users" RENAME TO "new_users"`
  },
  foreignKey: {
    simple: `ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id")`,
    cascade: `ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE`
  },
  addUniqueConstraint: {
    simple: `ALTER TABLE "users" ADD CONSTRAINT "AK_User_email" UNIQUE ("email")`
  },
  dropUniqueConstraint: {
    simple: `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "AK_User_email"`
  },
  comment: {
    commented: [
      `COMMENT ON TABLE "accounts" IS 'User accounts'`,
      `COMMENT ON COLUMN "accounts"."email" IS 'Login email'`
    ],
    none: []
  }
};
